### ISSUE TITLE
HostedUIProvidersCustomResourceInputs FAIL

### ISSUE THREAD

**Issue by marcobazzani** [awslabs/aws-amplify-identity-broker#426]
while running amplify publish I get
```
Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2023/02/26/[$LATEST]e1c0e7e82f5347d79baa40bd11f95dae (RequestId: 83c63d58-f990-44ee-b70d-2e44afaab5be)
```
this is the content of the stream:
```
START RequestId: 31e4f09e-7f42-459b-93e2-c6148056a602 Version: $LATEST
--
2023-02-26T13:11:40.324Z	31e4f09e-7f42-459b-93e2-c6148056a602	INFO	SyntaxError: Unexpected end of JSON input    at JSON.parse (<anonymous>)    at Runtime.exports.handler (/var/task/index.js:7:41)    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
2023-02-26T13:11:40.325Z	31e4f09e-7f42-459b-93e2-c6148056a602	INFO	Response body: {     "Status": "FAILED",     "Reason": "See the details in CloudWatch Log Stream: 2023/02/26/[$LATEST]e1c0e7e82f5347d79baa40bd11f95dae",     "PhysicalResourceId": "2023/02/26/[$LATEST]e1c0e7e82f5347d79baa40bd11f95dae",     "StackId": "arn:aws:cloudformation:eu-south-1:031163947536:stack/amplify-amplify-identity-broker-zdevox-140647-authamplifyIdentityBrokerAuth-PO3UA8MRVUNB/dbe721e0-b5d6-11ed-b5a5-0e35d8f71050",     "RequestId": "83c63d58-f990-44ee-b70d-2e44afaab5be",     "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",     "NoEcho": false,     "Data": {         "err": {}     } }

```
![Screenshot 2023-02-26 at 14 14 54](https://user-images.githubusercontent.com/6417589/221412623-3be05e2f-3ec6-47ac-822d-e920b13dce71.png)

it might be related to this change
![Screenshot 2023-02-26 at 14 22 29](https://user-images.githubusercontent.com/6417589/221412991-2c5a1125-72db-45f9-bbc5-8870f26f75a3.png)

but the doc just say keep them empty so did I

Any help would be appreciated

**Comment by marcobazzani** [comment]
In case someone stumble into it:
the list must exists in the json hostedUIProviderMeta

**Comment by maekawataiki** [comment]
Hi @marcobazzani 
Yes, empty `hostedUIProviderMeta` means empty list `"[]"` but not empty string `""`
Will update the doc
