### ISSUE TITLE
Cannot using access_token after /oauth2/token to get user from /oauth2/userInfo

### ISSUE THREAD

**Issue by rits423** [awslabs/aws-amplify-identity-broker#538]
I make the simple client with PKCE flow

I got access_token from api /oauth2/token but i can't using it to get user info from api  /oauth2/userInfo (broker or Cognito)

`"stack": "NotAuthorizedException: Invalid Access Token\n    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"`

**Comment by rits423** [comment]
sorry, my bad
